---
url: "https://avataxbr-sandbox.avalarabrasil.com.br/docs/index/api"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"
